routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use Illuminate\Support\Facades\Route;

Route::group(['namespace' => 'dashboard'], function () {

    Route::get('/', 'AuthController@login')->name('login');
    Route::post('/auth', 'AuthController@auth')->name('auth');

    Route::group(['prefix' => 'admin_dashboard', 'as' => 'admin_dashboard.', 'middleware' => ['web', 'auth']], function () {
        Route::get('logout', 'AuthController@logout')->name('logout');
        Route::get('/', 'HomeController@index')->name('index');

        Route::resource('user', 'UserController');
        Route::resource('provider', 'ProviderController');
        Route::resource('service', 'ServiceController');
        Route::resource('offers', 'OffersController');
        Route::resource('subservice', 'SubServiceController');
        Route::resource('order', 'OrderController');

        Route::get('sent', 'ContactController@sent')->name('contact.sent');
        Route::resource('contact', 'ContactController');
        Route::get('setting', 'SettingController@index')->name('setting.index');
        Route::post('setting/store', 'SettingController@store')->name('setting.store');
        Route::get('profile', 'SettingController@profile')->name('setting.profile');
        Route::post('profile/store/{admin}', 'SettingController@updateProfile')->name('setting.profile.update');
    });
});

app/Models/Offer.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Offer extends Model
{
    protected $guarded = ['id'];

    public function getImageUrlAttribute()
    {
        if($this->img != '') return asset('storage/app/public/images') .'/'. $this->img;
        return url('/public/dashboard/images/user.png');
    }
}

app/Http/Controllers/dashboard/AuthController.php
<?php

namespace App\Http\Controllers\dashboard;

use App\Http\Controllers\Controller;
use Illuminate\Foundation\Auth\AuthenticatesUsers;
use Illuminate\Http\Request;
use Auth;

class AuthController extends Controller
{
    //

     use AuthenticatesUsers;


    protected $redirectTo = '/';

    public function __construct()
    {
        $this->middleware('guest')->except('logout');
    }


    public function login()
    {
        return view('dashboard.auth.login');
    }


   public function auth(Request $request)
    {
        if (auth()->attempt(['email' => $request->email, 'password' => $request->password], true)) {
            return redirect()->route('admin_dashboard.index')->withTrue('مرحبا بك مره آخري');
        }else{
            return redirect()->route('login')->withFalse('بيانات غير صحيحه');
        }
    }

   public function logout()
    {
        Auth::guard('web')->logout();
        return redirect()->route('login')->withTrue('تم تسجيل الخروج');
    }

}

app/Http/Controllers/dashboard/ContactController.php
<?php

namespace App\Http\Controllers\dashboard;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Models\{Contact,User,Provider};
use App\Http\Requests\dashboard\ContactRequest;
class ContactController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $data = Contact::where('type','recive')->paginate(10);
        return view('dashboard.contact.index',compact('data'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $users = User::all();
        $providers = Provider::all();
        return view('dashboard.contact.create',compact('users','providers'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(ContactRequest $request)
    {
        $contact          = new Contact();
        $contact->from    = $request->from;
        if($contact->from =='user'){
          $contact->user_id    = $request->user_id;
        }elseif($contact->from =='provider'){
          $contact->provider_id = $request->provider_id;
        }
        $contact->subject = $request->subject;
        $contact->content = $request->content;
        $contact->type    = 'sent';

        $contact->save();

        return redirect()->back()->withTrue('تم الإضافة بنجاح');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Service $service)
    {
      return view('dashboard.services.edit',compact('service'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(ContactRequest $request, Contact $contact)
    {
        $contact->from    = $request->from;
        if($contact->from =='user'){
          $contact->user_id    = $request->user_id;
        }elseif($contact->from =='provider'){
          $contact->provider_id = $request->provider_id;
        }
        $contact->subject = $request->subject;
        $contact->content = $request->content;
        $contact->type    = 'sent';
        $service->save();
        return redirect()->back()->withTrue('تم التعديل بنجاح');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Contact $contact)
    {
        $contact->delete();
        return redirect()->back()->withTrue('تم الحذف بنجاح');
    }

    public function sent()
    {
        $data = Contact::where('type','sent')->paginate(10);
        return view('dashboard.contact.sent',compact('data'));
    }
}

app/Http/Controllers/dashboard/HomeController.php
<?php

namespace App\Http\Controllers\dashboard;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class HomeController extends Controller
{
    public function index()
    {
        $data = [];
        return view('dashboard.home.index',$data);
    }
}

app/Http/Controllers/dashboard/OffersController.php
<?php

namespace App\Http\Controllers\dashboard;

use App\Http\Controllers\Controller;
use App\Models\Offer;
use Exception;
use Illuminate\Contracts\View\Factory;
use Illuminate\Http\Request;
use App\Http\Requests\dashboard\OfferRequest;
use Illuminate\Http\Response;
use Illuminate\Support\Facades\File;
use Illuminate\View\View;

class OffersController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return Factory|View
     */
    public function index()
    {
        return view('dashboard.offers.index', ['data' => Offer::paginate(10)]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return Factory|View
     */
    public function create()
    {
        return view('dashboard.offers.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param OfferRequest $request
     * @return Response
     */
    public function store(OfferRequest $request)
    {
        $offer = new Offer();
        $offer->name = $request->name;
        $offer->desc = $request->desc;
        if ($request->image) {
            $offer->img = uploadImg($request->image);
        }
        $offer->save();

        return redirect()->back()->withTrue('تم الإضافة بنجاح');
    }

    /**
     * Display the specified resource.
     *
     * @param int $id
     * @return void
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param Offer $offer
     * @return Factory|View
     */
    public function edit(Offer $offer)
    {
        return view('dashboard.offers.edit', compact('offer'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param OfferRequest $request
     * @param Offer $offer
     * @return Response
     */
    public function update(OfferRequest $request, Offer $offer)
    {
        $offer->name = $request->name;
        $offer->desc = $request->desc;
        if ($request->image) {
            $offer->img = uploadImg($request->image);
        }
        $offer->save();
        return redirect()->back()->withTrue('تم التعديل بنجاح');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param Offer $offer
     * @return Response
     * @throws Exception
     */
    public function destroy(Offer $offer)
    {
        File::delete('storage/images/' . $offer->img);

        $offer->delete();

        return redirect()->back()->withTrue('تم الحذف بنجاح');
    }
}

app/Http/Controllers/dashboard/OrderController.php
<?php

namespace App\Http\Controllers\dashboard;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Models\Provider;
use App\Models\Service;
use App\Models\User;
use App\Models\Order;
use Carbon\Carbon;
use App\Http\Requests\dashboard\OrderRequest;

class OrderController extends Controller
{
   /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $data = Order::paginate(10);
        return view('dashboard.orders.index',compact('data'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $categories = Service::where('parent_id','!=',null)->get();
        $users = User::all();
        $providers = Provider::all();
        return view('dashboard.orders.create',compact('categories','users','providers'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(OrderRequest $request)
    {
        $order                = new Order();
        $order->provider_id   = $request->provider_id;
        $provider= Provider::find($request->provider_id);
        $order->user_id       = $request->user_id;
        $order->order_lat     = $request->order_lat;
        $order->order_lng     = $request->order_lng;
        $order->service_id    = $provider->service_id;
        $order->receive_lat   = $request->receive_lat;
        $order->receive_lng   = $request->receive_lng;
        $order->details       = $request->details;
        $order->status        = 'wait';
        $order->wait_date     = Carbon::now();
        $order->save();

        return redirect()->back()->withTrue('تم الإضافة بنجاح');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Order $order)
    {
       $categories = Service::where('parent_id','!=',null)->get();
       $users = User::all();
       $providers = Provider::all();
      return view('dashboard.orders.edit',compact('order','categories','providers','users'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(OrderRequest $request, Order $order)
    {
        $order->provider_id   = $request->provider_id;
        $provider             = Provider::find($request->provider_id);
        $order->user_id       = $request->user_id;
        $order->order_lat     = $request->order_lat;
        $order->order_lng     = $request->order_lng;
        $order->service_id    = $provider->service_id;
        $order->receive_lat   = $request->receive_lat;
        $order->receive_lng   = $request->receive_lng;
        $order->details       = $request->details;
        $order->save();
        return redirect()->back()->withTrue('تم التعديل بنجاح');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Order $order)
    {
        $order->delete();
        return redirect()->back()->withTrue('تم الحذف بنجاح');
    }

    public function changeStatus()
    {

    }
}

app/Http/Controllers/dashboard/ProviderController.php
<?php

namespace App\Http\Controllers\dashboard;

use App\Http\Controllers\Controller;
use Exception;
use Illuminate\Contracts\View\Factory;
use Illuminate\Http\Request;
use App\Models\Provider;
use App\Models\Service;
use App\Http\Requests\dashboard\ProviderRequest;
use App\Http\Requests\dashboard\EditProviderRequest;
use Illuminate\Http\Response;
use Illuminate\View\View;

class ProviderController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return Factory|View
     */
    public function index()
    {
        $data = Provider::paginate(10);
        return view('dashboard.customers.index', compact('data'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return Factory|View
     */
    public function create()
    {
        $categories = Service::where('parent_id', '!=', null)->get();
        return view('dashboard.customers.create', compact('categories'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param ProviderRequest $request
     * @return Response
     */
    public function store(ProviderRequest $request)
    {
        $user = new Provider();
        $user->name = $request->name;
        $user->email = $request->email;
        $user->mobile = $request->mobile;
        $user->city = $request->city;
        $user->service_id = $request->service_id;
        $user->identity = $request->identity;
        if ($request->identity_img) {
            $user->identity_img = uploadImg($request->identity_img);
        }
        $user->password = $request->password;
        $user->status = $request->status;
        $user->save();

        return redirect()->back()->withTrue('تم الإضافة بنجاح');
    }

    /**
     * Display the specified resource.
     *
     * @param int $id
     * @return void
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param Provider $provider
     * @return Factory|View
     */
    public function edit(Provider $provider)
    {
        $categories = Service::where('parent_id', '!=', null)->get();

        return view('dashboard.customers.edit', compact('provider', 'categories'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param EditProviderRequest $request
     * @param Provider $provider
     * @return Response
     */
    public function update(EditProviderRequest $request, Provider $provider)
    {
        $provider->name = $request->name;
        $provider->email = $request->email;
        $provider->mobile = $request->mobile;
        $provider->city = $request->city;
        $provider->service_id = $request->service_id;
        $provider->identity = $request->identity;

        if ($request->identity_img) {
            $provider->img = uploadImg($request->identity_img);
        }
        if ($request->password) {
            $provider->password = $request->password;
        }
        $provider->status = $request->status;
        $provider->save();
        return redirect()->back()->withTrue('تم التعديل بنجاح');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param Provider $provider
     * @return Response
     * @throws Exception
     */
    public function destroy(Provider $provider)
    {
        $provider->delete();
        return redirect()->back()->withTrue('تم الحذف بنجاح');
    }
}

resources/views/dashboard/admins/create.blade.php
@extends('dashboard.main.layout')
@section('css')
<link rel="stylesheet" href="{{asset('public/dashboard')}}/vendor/dropify/css/dropify.min.css">
<link rel="stylesheet" href="{{ asset('public/dashboard') }}/vendor/bootstrap-multiselect/bootstrap-multiselect.css">
<link rel="stylesheet" href="{{ asset('public/dashboard') }}/vendor/bootstrap-datepicker/css/bootstrap-datepicker3.min.css">
<link rel="stylesheet" href="{{ asset('public/dashboard') }}/vendor/bootstrap-colorpicker/css/bootstrap-colorpicker.css">
<link rel="stylesheet" href="{{ asset('public/dashboard') }}/vendor/multi-select/css/multi-select.css">

@endsection
@section('content')
        <div class="container-fluid">
            <div class="block-header">
                <div class="row clearfix">
                    <div class="col-md-6 col-sm-12">
                        <h1>الآقسام الفرعية للخدمات</h1>
                        <nav aria-label="breadcrumb">
                            <ol class="breadcrumb">
                            <li class="breadcrumb-item"><a href="#">الرئيسية</a></li>
                            <li class="breadcrumb-item"><a href="#">آقسام الخدمات الفرعية</a></li>
                            <li class="breadcrumb-item active" aria-current="page">إضافة</li>
                            </ol>
                        </nav>
                    </div>

                </div>
            </div>
            <div class="row clearfix">
                <div class="col-md-12">
                    <div class="card">
                        <div class="header">
                            <h2> الخدمات</h2>
                        </div>
                        <div class="body">
                            <form id="basic-form" method="post" action="{{route('admin_dashboard.subservice.store')}}" enctype="multipart/form-data">
                                @csrf
                                @include('dashboard.subservices.form')
                            </form>
                        </div>
                    </div>
                </div>

            </div>

        </div>
@endsection

@section('js')
<script src="{{ asset('public/dashboard') }}/vendor/dropify/js/dropify.js"></script>
<script src="{{ asset('public/dashboard') }}/bundles/mainscripts.bundle.js"></script>
<script src="{{ asset('public/dashboard') }}/js/pages/forms/dropify.js"></script>
<script src="{{ asset('public/dashboard') }}/vendor/jquery.maskedinput/jquery.maskedinput.min.js"></script>
<script src="{{ asset('public/dashboard') }}/vendor/multi-select/js/jquery.multi-select.js"></script><!-- Multi Select Plugin Js -->
<script src="{{ asset('public/dashboard') }}/vendor/bootstrap-multiselect/bootstrap-multiselect.js"></script>
<script src="{{ asset('public/dashboard') }}/vendor/bootstrap-datepicker/js/bootstrap-datepicker.min.js"></script>
@endsection

resources/views/dashboard/admins/edit.blade.php
@extends('dashboard.main.layout')
@section('css')
<link rel="stylesheet" href="{{asset('public/dashboard')}}/vendor/dropify/css/dropify.min.css">
<link rel="stylesheet" href="{{asset('public/dashboard')}}/vendor/dropify/css/dropify.min.css">
<link rel="stylesheet" href="{{ asset('public/dashboard') }}/vendor/bootstrap-multiselect/bootstrap-multiselect.css">
<link rel="stylesheet" href="{{ asset('public/dashboard') }}/vendor/bootstrap-datepicker/css/bootstrap-datepicker3.min.css">
<link rel="stylesheet" href="{{ asset('public/dashboard') }}/vendor/bootstrap-colorpicker/css/bootstrap-colorpicker.css">
<link rel="stylesheet" href="{{ asset('public/dashboard') }}/vendor/multi-select/css/multi-select.css">

@endsection
@section('content')
        <div class="container-fluid">
            <div class="block-header">
                <div class="row clearfix">
                    <div class="col-md-6 col-sm-12">
                        <h1>الآقسام الرئيسية للخدمات</h1>
                        <nav aria-label="breadcrumb">
                            <ol class="breadcrumb">
                            <li class="breadcrumb-item"><a href="#">الرئيسية</a></li>
                            <li class="breadcrumb-item"><a href="#">آقسام الخدمات الرئيسية</a></li>
                            <li class="breadcrumb-item active" aria-current="page">تعديل</li>
                            </ol>
                        </nav>
                    </div>

                </div>
            </div>
            <div class="row clearfix">
                <div class="col-md-12">
                    <div class="card">
                        <div class="header">
                            <h2> الخدمات</h2>
                        </div>
                        <div class="body">
                            <form id="basic-form" method="post" action="{{route('admin_dashboard.service.update',$service->id)}}" enctype="multipart/form-data">
                                @csrf
                                @method('PATCH')
                                @include('dashboard.services.form')
                            </form>
                        </div>
                    </div>
                </div>

            </div>

        </div>
@endsection

@section('js')
<script src="{{ asset('public/dashboard') }}/vendor/dropify/js/dropify.js"></script>
<script src="{{ asset('public/dashboard') }}/bundles/mainscripts.bundle.js"></script>
<script src="{{ asset('public/dashboard') }}/js/pages/forms/dropify.js"></script>
<script src="{{ asset('public/dashboard') }}/vendor/jquery.maskedinput/jquery.maskedinput.min.js"></script>
<script src="{{ asset('public/dashboard') }}/vendor/multi-select/js/jquery.multi-select.js"></script><!-- Multi Select Plugin Js -->
<script src="{{ asset('public/dashboard') }}/vendor/bootstrap-multiselect/bootstrap-multiselect.js"></script>
<script src="{{ asset('public/dashboard') }}/vendor/bootstrap-datepicker/js/bootstrap-datepicker.min.js"></script>
@endsection

resources/views/dashboard/admins/form.blade.php
<div class="form-group">
    <label>الإسم</label>
    <input type="text" class="form-control" placeholder="الإسم" @isset($service)
    value="{{$service->name}}"
           @endisset name="name">
</div>

<div class="form-group">
    <label>الوصف</label>
    <textarea class="form-control" rows="5" cols="30" name="desc" placeholder="الوصف">@isset($service)
            {{$service->desc}}
        @endisset</textarea>
</div>

<div class="form-group">
    <label> الصوره </label>
    <input type="file" class="dropify" name="image">
</div>
{{--  <div class="form-group">
    <label>Email Input</label>
    <input type="email" class="form-control" required>
</div>  --}}

{{--  <div class="form-group">
    <div class="row clearfix">
        <div class="col-lg-6 col-md-12">
            <label>Checkbox</label>
            <br/>
            <label class="fancy-checkbox">
                <input type="checkbox" name="checkbox" required data-parsley-errors-container="#error-checkbox">
                <span>Option 1</span>
            </label>
            <label class="fancy-checkbox">
                <input type="checkbox" name="checkbox">
                <span>Option 2</span>
            </label>
            <label class="fancy-checkbox">
                <input type="checkbox" name="checkbox">
                <span>Option 3</span>
            </label>
            <p id="error-checkbox"></p>
        </div>
        <div class="col-lg-6 col-md-12">
            <label>Radio Button</label>
            <br />
            <label class="fancy-radio">
                <input type="radio" name="gender" value="male" required data-parsley-errors-container="#error-radio">
                <span><i></i>Male</span>
            </label>
            <label class="fancy-radio">
                <input type="radio" name="gender" value="female">
                <span><i></i>Female</span>
            </label>
            <p id="error-radio"></p>
        </div>
    </div>
</div>
<div class="form-group">
    <label for="food">Multiselect</label>
    <br/>
    <div class="form-group">
        <select id="food" name="food[]" class="multiselect multiselect-custom" multiple="multiple" data-parsley-required data-parsley-trigger-after-failure="change" data-parsley-errors-container="#error-multiselect">
            <option value="cheese">Cheese</option>
            <option value="tomatoes">Tomatoes</option>
            <option value="mozarella">Mozzarella</option>
            <option value="mushrooms">Mushrooms</option>
            <option value="pepperoni">Pepperoni</option>
            <option value="onions">Onions</option>
        </select>
    </div>
    <p id="error-multiselect"></p>
</div>  --}}
<br>
<button type="submit" class="btn btn-primary">حفظ</button>

resources/views/dashboard/admins/index.blade.php
@extends('dashboard.main.layout')
@section('css')
<link rel="stylesheet" href="{{asset('public/dashboard') }}/vendor/jquery-datatable/dataTables.bootstrap4.min.css">
<link rel="stylesheet" href="{{ asset('public/dashboard') }}/vendor/jquery-datatable/fixedeader/dataTables.fixedcolumns.bootstrap4.min.css">
<link rel="stylesheet" href="{{ asset('public/dashboard') }}/vendor/jquery-datatable/fixedeader/dataTables.fixedheader.bootstrap4.min.css">
<link rel="stylesheet" href="{{ asset('public/dashboard') }}/vendor/sweetalert/sweetalert.css"/>


@endsection

@section('content')
<div class="container-fluid">
    <div class="block-header">
        <div class="row">
            <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
                <ul class="breadcrumb breadcrumb-style ">
                    <li class="breadcrumb-item">
                        <h4 class="page-title">Go App</h4>
                    </li>
                    <li class="breadcrumb-item bcrumb-1">
                        <a href="">
                            <i class="fas fa-home"></i> الرئيسية</a>
                    </li>
                    <li class="breadcrumb-item bcrumb-2">
                        <a href="#" onClick="return false;">الخدمات الرئيسية</a>
                    </li>
                    <li class="breadcrumb-item active">عرض البيانات</li>
                </ul>
            </div>
        </div>
    </div>

                <div class="row clearfix">
                <div class="col-lg-12">
                    <div class="card">
                        <div class="header">
                            <h2> الخدمات <small> الرئيسية </small></h2>
                        </div>
                        <div class="body">
                            <div class="table-responsive">
                                <table class="table table-hover js-basic-example dataTable table-custom spacing5">
                                    <thead>
                                        <tr>
                                            <th> # </th>
                                            <th>الاسم </th>
                                            <th>الوصف</th>
                                            <th>الصوره</th>
                                            <th colspan="2">خيارات</th>
                                        </tr>
                                    </thead>
                                    <tfoot>
                                        <tr>
                                            <th> # </th>
                                            <th>الاسم </th>
                                            <th>الوصف</th>
                                            <th>الصوره</th>
                                            <th colspan="2">خيارات</th>
                                        </tr>
                                    </tfoot>
                                    <tbody>
                                        @forelse ($data as $item)
                                          <tr>
                                            <td> {{ $loop->iteration }} </td>
                                            <td>{{ $item->name }}</td>
                                            <td>{{ $item->desc }}</td>
                                            <td> <img src="{{ $item->image_url }}" data-toggle="tooltip" data-placement="top" title="" alt="Avatar" class="w35 h35 rounded" data-original-title="Avatar Name"></td>
                                            <td><a class="btn btn-info" href="{{ route('admin_dashboard.service.edit',$item->id) }}"> <i class="fa fa-edit"></i> تعديل </a></td>
                                            <td><form method="post" action="{{route('admin_dashboard.service.destroy',$item->id) }}"> @method('DELETE') @csrf <button type="submit" class="btn btn-danger"> <i class="fa fa-trash-o"></i> حذف </button>  </form></td>
                                          </tr>
                                        @empty
                                            <td colspan="6"> لايوجد بيانات متوفره</td>
                                        @endforelse
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>

            </div>

</div>
@endsection

@section('js')
<script src="{{asset('public/dashboard')}}/bundles/datatablescripts.bundle.js"></script>
<script src="{{asset('public/dashboard') }}/vendor/jquery-datatable/buttons/dataTables.buttons.min.js"></script>
<script src="{{asset('public/dashboard') }}/vendor/jquery-datatable/buttons/buttons.bootstrap4.min.js"></script>
<script src="{{ asset('public/dashboard') }}/vendor/jquery-datatable/buttons/buttons.colVis.min.js"></script>
<script src="{{ asset('public/dashboard') }}/vendor/jquery-datatable/buttons/buttons.html5.min.js"></script>
<script src="{{ asset('public/dashboard') }}/vendor/jquery-datatable/buttons/buttons.print.min.js"></script>
<script src="{{ asset('public/dashboard') }}/vendor/sweetalert/sweetalert.min.js"></script><!-- SweetAlert Plugin Js -->
<script src="{{ asset('public/dashboard') }}/js/pages/tables/jquery-datatable.js"></script>

@endsection