routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use Illuminate\Support\Facades\Route;

Route::group(['namespace' => 'dashboard'], function () {

    Route::get('/', 'AuthController@login')->name('login');
    Route::post('/auth', 'AuthController@auth')->name('auth');

    Route::group(['prefix' => 'admin_dashboard', 'as' => 'admin_dashboard.', 'middleware' => ['web', 'auth']], function () {
        Route::get('logout', 'AuthController@logout')->name('logout');
        Route::get('/', 'HomeController@index')->name('index');

        Route::resource('user', 'UserController');
        Route::resource('provider', 'ProviderController');
        Route::resource('service', 'ServiceController');
        Route::resource('offers', 'OffersController');
        Route::resource('subservice', 'SubServiceController');
        Route::resource('order', 'OrderController');

        Route::get('sent', 'ContactController@sent')->name('contact.sent');
        Route::resource('contact', 'ContactController');
        Route::get('setting', 'SettingController@index')->name('setting.index');
        Route::post('setting/store', 'SettingController@store')->name('setting.store');
        Route::get('profile', 'SettingController@profile')->name('setting.profile');
        Route::post('profile/store/{admin}', 'SettingController@updateProfile')->name('setting.profile.update');
    });
});

app/Models/Provider.php
<?php

namespace App\Models;
use App\Events\SendResetCodeMailEvent;
use App\Http\Resources\ProviderResource;
use Exception;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\DB;
use Tymon\JWTAuth\Contracts\JWTSubject;
use Illuminate\Database\Eloquent\Model;

class Provider extends Authenticatable implements JWTSubject
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $guarded = ['id', 'device_token'];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    public function getJWTIdentifier()
    {
        return $this->getKey();
    }

    public function getJWTCustomClaims()
    {
        return [];
    }
    public function token()
    {
        return $this->hasOne('App\Models\ProviderToken');
    }

    public function notifications()
    {
        return $this->hasMany('App\Models\ProviderNotification','provider_id','id');
    }

    public function service()
    {
        return $this->belongsTo('App\Models\Service');
    }

    public function getIdentityImgUrlAttribute()
    {
        if($this->identity_img != '') return url('public/uploaded/providers/' . $this->identity_img);
        else return url('public/dashboard/images/user.png');
    }

    public function setPasswordAttribute($password)
    {
        if ( !empty($password) ) {
            $this->attributes['password'] = bcrypt($password);
        }
    }

    public static function apiProviderLogin($request)
    {
        $provider = Provider::whereMobile($request->mobile)->first();

        if($provider->status == 0) return apiResponse([], 'success', null, 'عفوا هذا الحساب غير مفعل من الادارة حاليا', 203);

        if (!$token = Auth::guard('provider')->attempt($request->only('mobile','password'))) return apiResponse([],'success',null,trans('auth.failed'), 203);

        if(!auth()->guard('provider')->user()->token)
        {
            ProviderToken::createToken($request, auth()->guard('provider')->user(), $token);
        }

        else auth()->guard('provider')->user()->token->update(['jwt' => $token, 'ip' => $request->ip()]);

        if(!auth()->guard('provider')->user()->fcm)
        {
            FcmProvider::create(['provider_id' => auth()->guard('provider')->user()->id,'fcm_token' => $request->device_token]);
        }

        else auth()->guard('provider')->user()->fcm->update(['fcm_token' => $request->device_token]);

        return apiResponse(new ProviderResource($provider), 'success');
    }

    public static function apiProviderRegister($request)
    {
        DB::beginTransaction();
        try
        {
            $providerData = $request->all();

            if($request->hasFile('identity_img')) $providerData['identity_img'] = uploaded($request->identity_img,'provider');

            else $providerData['identity_img'] = arr()->except($providerData,['identity_img']);

            $createdProvider = Provider::create($providerData);

            // get the user token;
            $jwt = Auth::guard('provider')->fromUser($createdProvider);

            // add the user id and generated token;
            ProviderToken::createToken($request, $createdProvider, $jwt);

            // create or update firebase token;
            FcmProvider::createFcmProvider($createdProvider, $request);

            DB::commit();

            return apiResponse(new ProviderResource($createdProvider), 'success');
        }
        catch(Exception $e)
        {
            DB::rollBack();
            return apiResponse([], 'fails', null, $e->getMessage());
        }
    }

    public static function apiForgetPassword($request)
    {
        try
        {
            $provider = Provider::whereEmail($request->email)->first();

            $code = create_rand_numbers(8);

            $provider->update(['code' => $code]);

            $mess = "كود إعادة تعين كلمة المرور الخاص بك هو : $code";

            event(new SendResetCodeMailEvent($provider, $mess));

            return apiResponse([], 'success', null, 'تم ارسال كود اعادة التعين بنجاح');
        }
        catch (Exception $e)
        {
            return apiResponse([], 'fails', null, $e->getMessage());
        }
    }

    public function orders()
    {
        return $this->hasMany(Order::class, 'provider_id', 'id');
    }
}

app/Http/Controllers/dashboard/AuthController.php
<?php

namespace App\Http\Controllers\dashboard;

use App\Http\Controllers\Controller;
use Illuminate\Foundation\Auth\AuthenticatesUsers;
use Illuminate\Http\Request;
use Auth;

class AuthController extends Controller
{
    //

     use AuthenticatesUsers;


    protected $redirectTo = '/';

    public function __construct()
    {
        $this->middleware('guest')->except('logout');
    }


    public function login()
    {
        return view('dashboard.auth.login');
    }


   public function auth(Request $request)
    {
        if (auth()->attempt(['email' => $request->email, 'password' => $request->password], true)) {
            return redirect()->route('admin_dashboard.index')->withTrue('مرحبا بك مره آخري');
        }else{
            return redirect()->route('login')->withFalse('بيانات غير صحيحه');
        }
    }

   public function logout()
    {
        Auth::guard('web')->logout();
        return redirect()->route('login')->withTrue('تم تسجيل الخروج');
    }

}

app/Http/Controllers/dashboard/ContactController.php
<?php

namespace App\Http\Controllers\dashboard;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Models\{Contact,User,Provider};
use App\Http\Requests\dashboard\ContactRequest;
class ContactController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $data = Contact::where('type','recive')->paginate(10);
        return view('dashboard.contact.index',compact('data'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $users = User::all();
        $providers = Provider::all();
        return view('dashboard.contact.create',compact('users','providers'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(ContactRequest $request)
    {
        $contact          = new Contact();
        $contact->from    = $request->from;
        if($contact->from =='user'){
          $contact->user_id    = $request->user_id;
        }elseif($contact->from =='provider'){
          $contact->provider_id = $request->provider_id;
        }
        $contact->subject = $request->subject;
        $contact->content = $request->content;
        $contact->type    = 'sent';

        $contact->save();

        return redirect()->back()->withTrue('تم الإضافة بنجاح');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Service $service)
    {
      return view('dashboard.services.edit',compact('service'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(ContactRequest $request, Contact $contact)
    {
        $contact->from    = $request->from;
        if($contact->from =='user'){
          $contact->user_id    = $request->user_id;
        }elseif($contact->from =='provider'){
          $contact->provider_id = $request->provider_id;
        }
        $contact->subject = $request->subject;
        $contact->content = $request->content;
        $contact->type    = 'sent';
        $service->save();
        return redirect()->back()->withTrue('تم التعديل بنجاح');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Contact $contact)
    {
        $contact->delete();
        return redirect()->back()->withTrue('تم الحذف بنجاح');
    }

    public function sent()
    {
        $data = Contact::where('type','sent')->paginate(10);
        return view('dashboard.contact.sent',compact('data'));
    }
}

app/Http/Controllers/dashboard/HomeController.php
<?php

namespace App\Http\Controllers\dashboard;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class HomeController extends Controller
{
    public function index()
    {
        $data = [];
        return view('dashboard.home.index',$data);
    }
}

app/Http/Controllers/dashboard/OffersController.php
<?php

namespace App\Http\Controllers\dashboard;

use App\Http\Controllers\Controller;
use App\Models\Offer;
use Exception;
use Illuminate\Contracts\View\Factory;
use Illuminate\Http\Request;
use App\Http\Requests\dashboard\OfferRequest;
use Illuminate\Http\Response;
use Illuminate\Support\Facades\File;
use Illuminate\View\View;

class OffersController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return Factory|View
     */
    public function index()
    {
        return view('dashboard.offers.index', ['data' => Offer::paginate(10)]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return Factory|View
     */
    public function create()
    {
        return view('dashboard.offers.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param OfferRequest $request
     * @return Response
     */
    public function store(OfferRequest $request)
    {
        $offer = new Offer();
        $offer->name = $request->name;
        $offer->desc = $request->desc;
        if ($request->image) {
            $offer->img = uploadImg($request->image);
        }
        $offer->save();

        return redirect()->back()->withTrue('تم الإضافة بنجاح');
    }

    /**
     * Display the specified resource.
     *
     * @param int $id
     * @return void
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param Offer $offer
     * @return Factory|View
     */
    public function edit(Offer $offer)
    {
        return view('dashboard.offers.edit', compact('offer'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param OfferRequest $request
     * @param Offer $offer
     * @return Response
     */
    public function update(OfferRequest $request, Offer $offer)
    {
        $offer->name = $request->name;
        $offer->desc = $request->desc;
        if ($request->image) {
            $offer->img = uploadImg($request->image);
        }
        $offer->save();
        return redirect()->back()->withTrue('تم التعديل بنجاح');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param Offer $offer
     * @return Response
     * @throws Exception
     */
    public function destroy(Offer $offer)
    {
        File::delete('storage/images/' . $offer->img);

        $offer->delete();

        return redirect()->back()->withTrue('تم الحذف بنجاح');
    }
}

app/Http/Controllers/dashboard/OrderController.php
<?php

namespace App\Http\Controllers\dashboard;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Models\Provider;
use App\Models\Service;
use App\Models\User;
use App\Models\Order;
use Carbon\Carbon;
use App\Http\Requests\dashboard\OrderRequest;

class OrderController extends Controller
{
   /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $data = Order::paginate(10);
        return view('dashboard.orders.index',compact('data'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $categories = Service::where('parent_id','!=',null)->get();
        $users = User::all();
        $providers = Provider::all();
        return view('dashboard.orders.create',compact('categories','users','providers'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(OrderRequest $request)
    {
        $order                = new Order();
        $order->provider_id   = $request->provider_id;
        $provider= Provider::find($request->provider_id);
        $order->user_id       = $request->user_id;
        $order->order_lat     = $request->order_lat;
        $order->order_lng     = $request->order_lng;
        $order->service_id    = $provider->service_id;
        $order->receive_lat   = $request->receive_lat;
        $order->receive_lng   = $request->receive_lng;
        $order->details       = $request->details;
        $order->status        = 'wait';
        $order->wait_date     = Carbon::now();
        $order->save();

        return redirect()->back()->withTrue('تم الإضافة بنجاح');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Order $order)
    {
       $categories = Service::where('parent_id','!=',null)->get();
       $users = User::all();
       $providers = Provider::all();
      return view('dashboard.orders.edit',compact('order','categories','providers','users'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(OrderRequest $request, Order $order)
    {
        $order->provider_id   = $request->provider_id;
        $provider             = Provider::find($request->provider_id);
        $order->user_id       = $request->user_id;
        $order->order_lat     = $request->order_lat;
        $order->order_lng     = $request->order_lng;
        $order->service_id    = $provider->service_id;
        $order->receive_lat   = $request->receive_lat;
        $order->receive_lng   = $request->receive_lng;
        $order->details       = $request->details;
        $order->save();
        return redirect()->back()->withTrue('تم التعديل بنجاح');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Order $order)
    {
        $order->delete();
        return redirect()->back()->withTrue('تم الحذف بنجاح');
    }

    public function changeStatus()
    {

    }
}

resources/views/dashboard/customers/create.blade.php
@extends('dashboard.main.layout')
@section('css')
<link rel="stylesheet" href="{{asset('public/dashboard')}}/vendor/dropify/css/dropify.min.css">
<link rel="stylesheet" href="{{ asset('public/dashboard') }}/vendor/bootstrap-multiselect/bootstrap-multiselect.css">
<link rel="stylesheet" href="{{ asset('public/dashboard') }}/vendor/bootstrap-datepicker/css/bootstrap-datepicker3.min.css">
<link rel="stylesheet" href="{{ asset('public/dashboard') }}/vendor/bootstrap-colorpicker/css/bootstrap-colorpicker.css">
<link rel="stylesheet" href="{{ asset('public/dashboard') }}/vendor/multi-select/css/multi-select.css">

@endsection
@section('content')
        <div class="container-fluid">
            <div class="block-header">
                <div class="row clearfix">
                    <div class="col-md-6 col-sm-12">
                        <h1>مقدمين للخدمات</h1>
                        <nav aria-label="breadcrumb">
                            <ol class="breadcrumb">
                            <li class="breadcrumb-item"><a href="#">الرئيسية</a></li>
                            <li class="breadcrumb-item"><a href="#">مقدمين الخدمات </a></li>
                            <li class="breadcrumb-item active" aria-current="page">إضافة</li>
                            </ol>
                        </nav>
                    </div>

                </div>
            </div>
            <div class="row clearfix">
                <div class="col-md-12">
                    <div class="card">
                        <div class="header">
                            <h2> الخدمات</h2>
                        </div>
                        <div class="body">
                            <form id="basic-form" method="post" action="{{route('admin_dashboard.provider.store')}}" enctype="multipart/form-data">
                                @csrf
                                @include('dashboard.customers.form')
                            </form>
                        </div>
                    </div>
                </div>

            </div>

        </div>
@endsection

@section('js')
<script src="{{ asset('public/dashboard') }}/vendor/dropify/js/dropify.js"></script>
<script src="{{ asset('public/dashboard') }}/bundles/mainscripts.bundle.js"></script>
<script src="{{ asset('public/dashboard') }}/js/pages/forms/dropify.js"></script>
<script src="{{ asset('public/dashboard') }}/vendor/jquery.maskedinput/jquery.maskedinput.min.js"></script>
<script src="{{ asset('public/dashboard') }}/vendor/multi-select/js/jquery.multi-select.js"></script><!-- Multi Select Plugin Js -->
<script src="{{ asset('public/dashboard') }}/vendor/bootstrap-multiselect/bootstrap-multiselect.js"></script>
<script src="{{ asset('public/dashboard') }}/vendor/bootstrap-datepicker/js/bootstrap-datepicker.min.js"></script>
@endsection

resources/views/dashboard/customers/edit.blade.php
@extends('dashboard.main.layout')
@section('css')
<link rel="stylesheet" href="{{asset('public/dashboard')}}/vendor/dropify/css/dropify.min.css">
<link rel="stylesheet" href="{{asset('public/dashboard')}}/vendor/dropify/css/dropify.min.css">
<link rel="stylesheet" href="{{ asset('public/dashboard') }}/vendor/bootstrap-multiselect/bootstrap-multiselect.css">
<link rel="stylesheet" href="{{ asset('public/dashboard') }}/vendor/bootstrap-datepicker/css/bootstrap-datepicker3.min.css">
<link rel="stylesheet" href="{{ asset('public/dashboard') }}/vendor/bootstrap-colorpicker/css/bootstrap-colorpicker.css">
<link rel="stylesheet" href="{{ asset('public/dashboard') }}/vendor/multi-select/css/multi-select.css">

@endsection
@section('content')
        <div class="container-fluid">
            <div class="block-header">
                <div class="row clearfix">
                    <div class="col-md-6 col-sm-12">
                        <h1>مقدمين  للخدمات</h1>
                        <nav aria-label="breadcrumb">
                            <ol class="breadcrumb">
                            <li class="breadcrumb-item"><a href="#">الرئيسية</a></li>
                            <li class="breadcrumb-item"><a href="#"> الخدمات مقدمين</a></li>
                            <li class="breadcrumb-item active" aria-current="page">تعديل</li>
                            </ol>
                        </nav>
                    </div>

                </div>
            </div>
            <div class="row clearfix">
                <div class="col-md-12">
                    <div class="card">
                        <div class="header">
                            <h2> الخدمات</h2>
                        </div>
                        <div class="body">
                            <form id="basic-form" method="post" action="{{route('admin_dashboard.provider.update',$provider->id)}}" enctype="multipart/form-data">
                                @csrf
                                @method('PATCH')
                                @include('dashboard.customers.form')
                            </form>
                        </div>
                    </div>
                </div>

            </div>

        </div>
@endsection

@section('js')
<script src="{{ asset('public/dashboard') }}/vendor/dropify/js/dropify.js"></script>
<script src="{{ asset('public/dashboard') }}/bundles/mainscripts.bundle.js"></script>
<script src="{{ asset('public/dashboard') }}/js/pages/forms/dropify.js"></script>
<script src="{{ asset('public/dashboard') }}/vendor/jquery.maskedinput/jquery.maskedinput.min.js"></script>
<script src="{{ asset('public/dashboard') }}/vendor/multi-select/js/jquery.multi-select.js"></script><!-- Multi Select Plugin Js -->
<script src="{{ asset('public/dashboard') }}/vendor/bootstrap-multiselect/bootstrap-multiselect.js"></script>
<script src="{{ asset('public/dashboard') }}/vendor/bootstrap-datepicker/js/bootstrap-datepicker.min.js"></script>
@endsection

resources/views/dashboard/customers/index.blade.php
@extends('dashboard.main.layout')
@section('css')
    <link rel="stylesheet" href="{{asset('public/dashboard') }}/vendor/jquery-datatable/dataTables.bootstrap4.min.css">
    <link rel="stylesheet"
          href="{{ asset('public/dashboard') }}/vendor/jquery-datatable/fixedeader/dataTables.fixedcolumns.bootstrap4.min.css">
    <link rel="stylesheet"
          href="{{ asset('public/dashboard') }}/vendor/jquery-datatable/fixedeader/dataTables.fixedheader.bootstrap4.min.css">
    <link rel="stylesheet" href="{{ asset('public/dashboard') }}/vendor/sweetalert/sweetalert.css"/>


@endsection

@section('content')
    <div class="container-fluid">
        <div class="block-header">
            <div class="row">
                <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
                    <ul class="breadcrumb breadcrumb-style ">
                        <li class="breadcrumb-item">
                            <h4 class="page-title">Go App</h4>
                        </li>
                        <li class="breadcrumb-item bcrumb-1">
                            <a href="">
                                <i class="fas fa-home"></i> الرئيسية</a>
                        </li>
                        <li class="breadcrumb-item bcrumb-2">
                            <a href="#" onClick="return false;">الخدمات مقدمي</a>
                        </li>
                        <li class="breadcrumb-item active">عرض البيانات</li>
                    </ul>
                </div>
            </div>
        </div>

        <div class="row clearfix">
            <div class="col-lg-12">
                <div class="card">
                    <div class="header">
                        <h2> الخدمات <small> مقدمي </small></h2>
                    </div>
                    <div class="body">
                        <div class="table-responsive">
                            <table class="table table-hover js-basic-example dataTable table-custom spacing5">
                                <thead>
                                <tr>
                                    <th> #</th>
                                    <th>الاسم</th>
                                    <th>البريد الإلكتروني</th>
                                    <th>الصوره</th>
                                    <th> القسم</th>
                                    <th colspan="2">خيارات</th>
                                </tr>
                                </thead>
                                <tfoot>
                                <tr>
                                    <th> #</th>
                                    <th>الاسم</th>
                                    <th>البريد الإلكتروني</th>
                                    <th>الصوره</th>
                                    <th> القسم</th>
                                    <th colspan="2">خيارات</th>
                                </tr>
                                </tfoot>
                                <tbody>
                                @forelse ($data as $item)
                                    <tr>
                                        <td> {{ $loop->iteration }} </td>
                                        <td>{{ $item->name }}</td>
                                        <td>{{ $item->email }}</td>
                                        <td><img src="{{ $item->identity_img_url }}" data-toggle="tooltip" data-placement="top"
                                                 title="" alt="Avatar" class="w35 h35 rounded"
                                                 data-original-title="Avatar Name"></td>
                                        <td>{{ $item->service->name }}</td>
                                        <td><a class="btn btn-info"
                                               href="{{ route('admin_dashboard.provider.edit',$item->id) }}"> <i
                                                    class="fa fa-edit"></i> تعديل </a></td>
                                        <td>
                                            <form method="post"
                                                  action="{{route('admin_dashboard.provider.destroy',$item->id) }}"> @method('DELETE') @csrf
                                                <button type="submit" class="btn btn-danger"><i
                                                        class="fa fa-trash-o"></i> حذف
                                                </button>
                                            </form>
                                        </td>
                                    </tr>
                                @empty
                                    <td colspan="6"> لايوجد بيانات متوفره</td>
                                @endforelse
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>

        </div>

    </div>
@endsection

@section('js')
    <script src="{{asset('public/dashboard')}}/bundles/datatablescripts.bundle.js"></script>
    <script src="{{asset('public/dashboard') }}/vendor/jquery-datatable/buttons/dataTables.buttons.min.js"></script>
    <script src="{{asset('public/dashboard') }}/vendor/jquery-datatable/buttons/buttons.bootstrap4.min.js"></script>
    <script src="{{ asset('public/dashboard') }}/vendor/jquery-datatable/buttons/buttons.colVis.min.js"></script>
    <script src="{{ asset('public/dashboard') }}/vendor/jquery-datatable/buttons/buttons.html5.min.js"></script>
    <script src="{{ asset('public/dashboard') }}/vendor/jquery-datatable/buttons/buttons.print.min.js"></script>
    <script
        src="{{ asset('public/dashboard') }}/vendor/sweetalert/sweetalert.min.js"></script><!-- SweetAlert Plugin Js -->
    <script src="{{ asset('public/dashboard') }}/js/pages/tables/jquery-datatable.js"></script>

@endsection