routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use Illuminate\Support\Facades\Route;

Route::group(['namespace' => 'dashboard'], function () {

    Route::get('/', 'AuthController@login')->name('login');
    Route::post('/auth', 'AuthController@auth')->name('auth');

    Route::group(['prefix' => 'admin_dashboard', 'as' => 'admin_dashboard.', 'middleware' => ['web', 'auth']], function () {
        Route::get('logout', 'AuthController@logout')->name('logout');
        Route::get('/', 'HomeController@index')->name('index');

        Route::resource('user', 'UserController');
        Route::resource('provider', 'ProviderController');
        Route::resource('service', 'ServiceController');
        Route::resource('offers', 'OffersController');
        Route::resource('subservice', 'SubServiceController');
        Route::resource('order', 'OrderController');

        Route::get('sent', 'ContactController@sent')->name('contact.sent');
        Route::resource('contact', 'ContactController');
        Route::get('setting', 'SettingController@index')->name('setting.index');
        Route::post('setting/store', 'SettingController@store')->name('setting.store');
        Route::get('profile', 'SettingController@profile')->name('setting.profile');
        Route::post('profile/store/{admin}', 'SettingController@updateProfile')->name('setting.profile.update');
    });
});

app/Http/Controllers/dashboard/AuthController.php
<?php

namespace App\Http\Controllers\dashboard;

use App\Http\Controllers\Controller;
use Illuminate\Foundation\Auth\AuthenticatesUsers;
use Illuminate\Http\Request;
use Auth;

class AuthController extends Controller
{
    //

     use AuthenticatesUsers;


    protected $redirectTo = '/';

    public function __construct()
    {
        $this->middleware('guest')->except('logout');
    }


    public function login()
    {
        return view('dashboard.auth.login');
    }


   public function auth(Request $request)
    {
        if (auth()->attempt(['email' => $request->email, 'password' => $request->password], true)) {
            return redirect()->route('admin_dashboard.index')->withTrue('مرحبا بك مره آخري');
        }else{
            return redirect()->route('login')->withFalse('بيانات غير صحيحه');
        }
    }

   public function logout()
    {
        Auth::guard('web')->logout();
        return redirect()->route('login')->withTrue('تم تسجيل الخروج');
    }

}

app/Http/Controllers/dashboard/ContactController.php
<?php

namespace App\Http\Controllers\dashboard;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Models\{Contact,User,Provider};
use App\Http\Requests\dashboard\ContactRequest;
class ContactController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $data = Contact::where('type','recive')->paginate(10);
        return view('dashboard.contact.index',compact('data'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $users = User::all();
        $providers = Provider::all();
        return view('dashboard.contact.create',compact('users','providers'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(ContactRequest $request)
    {
        $contact          = new Contact();
        $contact->from    = $request->from;
        if($contact->from =='user'){
          $contact->user_id    = $request->user_id;
        }elseif($contact->from =='provider'){
          $contact->provider_id = $request->provider_id;
        }
        $contact->subject = $request->subject;
        $contact->content = $request->content;
        $contact->type    = 'sent';

        $contact->save();

        return redirect()->back()->withTrue('تم الإضافة بنجاح');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Service $service)
    {
      return view('dashboard.services.edit',compact('service'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(ContactRequest $request, Contact $contact)
    {
        $contact->from    = $request->from;
        if($contact->from =='user'){
          $contact->user_id    = $request->user_id;
        }elseif($contact->from =='provider'){
          $contact->provider_id = $request->provider_id;
        }
        $contact->subject = $request->subject;
        $contact->content = $request->content;
        $contact->type    = 'sent';
        $service->save();
        return redirect()->back()->withTrue('تم التعديل بنجاح');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Contact $contact)
    {
        $contact->delete();
        return redirect()->back()->withTrue('تم الحذف بنجاح');
    }

    public function sent()
    {
        $data = Contact::where('type','sent')->paginate(10);
        return view('dashboard.contact.sent',compact('data'));
    }
}

app/Http/Controllers/dashboard/HomeController.php
<?php

namespace App\Http\Controllers\dashboard;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class HomeController extends Controller
{
    public function index()
    {
        $data = [];
        return view('dashboard.home.index',$data);
    }
}

app/Http/Controllers/dashboard/OffersController.php
<?php

namespace App\Http\Controllers\dashboard;

use App\Http\Controllers\Controller;
use App\Models\Offer;
use Exception;
use Illuminate\Contracts\View\Factory;
use Illuminate\Http\Request;
use App\Http\Requests\dashboard\OfferRequest;
use Illuminate\Http\Response;
use Illuminate\Support\Facades\File;
use Illuminate\View\View;

class OffersController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return Factory|View
     */
    public function index()
    {
        return view('dashboard.offers.index', ['data' => Offer::paginate(10)]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return Factory|View
     */
    public function create()
    {
        return view('dashboard.offers.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param OfferRequest $request
     * @return Response
     */
    public function store(OfferRequest $request)
    {
        $offer = new Offer();
        $offer->name = $request->name;
        $offer->desc = $request->desc;
        if ($request->image) {
            $offer->img = uploadImg($request->image);
        }
        $offer->save();

        return redirect()->back()->withTrue('تم الإضافة بنجاح');
    }

    /**
     * Display the specified resource.
     *
     * @param int $id
     * @return void
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param Offer $offer
     * @return Factory|View
     */
    public function edit(Offer $offer)
    {
        return view('dashboard.offers.edit', compact('offer'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param OfferRequest $request
     * @param Offer $offer
     * @return Response
     */
    public function update(OfferRequest $request, Offer $offer)
    {
        $offer->name = $request->name;
        $offer->desc = $request->desc;
        if ($request->image) {
            $offer->img = uploadImg($request->image);
        }
        $offer->save();
        return redirect()->back()->withTrue('تم التعديل بنجاح');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param Offer $offer
     * @return Response
     * @throws Exception
     */
    public function destroy(Offer $offer)
    {
        File::delete('storage/images/' . $offer->img);

        $offer->delete();

        return redirect()->back()->withTrue('تم الحذف بنجاح');
    }
}

app/Http/Controllers/dashboard/OrderController.php
<?php

namespace App\Http\Controllers\dashboard;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Models\Provider;
use App\Models\Service;
use App\Models\User;
use App\Models\Order;
use Carbon\Carbon;
use App\Http\Requests\dashboard\OrderRequest;

class OrderController extends Controller
{
   /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $data = Order::paginate(10);
        return view('dashboard.orders.index',compact('data'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $categories = Service::where('parent_id','!=',null)->get();
        $users = User::all();
        $providers = Provider::all();
        return view('dashboard.orders.create',compact('categories','users','providers'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(OrderRequest $request)
    {
        $order                = new Order();
        $order->provider_id   = $request->provider_id;
        $provider= Provider::find($request->provider_id);
        $order->user_id       = $request->user_id;
        $order->order_lat     = $request->order_lat;
        $order->order_lng     = $request->order_lng;
        $order->service_id    = $provider->service_id;
        $order->receive_lat   = $request->receive_lat;
        $order->receive_lng   = $request->receive_lng;
        $order->details       = $request->details;
        $order->status        = 'wait';
        $order->wait_date     = Carbon::now();
        $order->save();

        return redirect()->back()->withTrue('تم الإضافة بنجاح');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Order $order)
    {
       $categories = Service::where('parent_id','!=',null)->get();
       $users = User::all();
       $providers = Provider::all();
      return view('dashboard.orders.edit',compact('order','categories','providers','users'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(OrderRequest $request, Order $order)
    {
        $order->provider_id   = $request->provider_id;
        $provider             = Provider::find($request->provider_id);
        $order->user_id       = $request->user_id;
        $order->order_lat     = $request->order_lat;
        $order->order_lng     = $request->order_lng;
        $order->service_id    = $provider->service_id;
        $order->receive_lat   = $request->receive_lat;
        $order->receive_lng   = $request->receive_lng;
        $order->details       = $request->details;
        $order->save();
        return redirect()->back()->withTrue('تم التعديل بنجاح');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Order $order)
    {
        $order->delete();
        return redirect()->back()->withTrue('تم الحذف بنجاح');
    }

    public function changeStatus()
    {

    }
}

app/Http/Controllers/dashboard/ProviderController.php
<?php

namespace App\Http\Controllers\dashboard;

use App\Http\Controllers\Controller;
use Exception;
use Illuminate\Contracts\View\Factory;
use Illuminate\Http\Request;
use App\Models\Provider;
use App\Models\Service;
use App\Http\Requests\dashboard\ProviderRequest;
use App\Http\Requests\dashboard\EditProviderRequest;
use Illuminate\Http\Response;
use Illuminate\View\View;

class ProviderController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return Factory|View
     */
    public function index()
    {
        $data = Provider::paginate(10);
        return view('dashboard.customers.index', compact('data'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return Factory|View
     */
    public function create()
    {
        $categories = Service::where('parent_id', '!=', null)->get();
        return view('dashboard.customers.create', compact('categories'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param ProviderRequest $request
     * @return Response
     */
    public function store(ProviderRequest $request)
    {
        $user = new Provider();
        $user->name = $request->name;
        $user->email = $request->email;
        $user->mobile = $request->mobile;
        $user->city = $request->city;
        $user->service_id = $request->service_id;
        $user->identity = $request->identity;
        if ($request->identity_img) {
            $user->identity_img = uploadImg($request->identity_img);
        }
        $user->password = $request->password;
        $user->status = $request->status;
        $user->save();

        return redirect()->back()->withTrue('تم الإضافة بنجاح');
    }

    /**
     * Display the specified resource.
     *
     * @param int $id
     * @return void
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param Provider $provider
     * @return Factory|View
     */
    public function edit(Provider $provider)
    {
        $categories = Service::where('parent_id', '!=', null)->get();

        return view('dashboard.customers.edit', compact('provider', 'categories'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param EditProviderRequest $request
     * @param Provider $provider
     * @return Response
     */
    public function update(EditProviderRequest $request, Provider $provider)
    {
        $provider->name = $request->name;
        $provider->email = $request->email;
        $provider->mobile = $request->mobile;
        $provider->city = $request->city;
        $provider->service_id = $request->service_id;
        $provider->identity = $request->identity;

        if ($request->identity_img) {
            $provider->img = uploadImg($request->identity_img);
        }
        if ($request->password) {
            $provider->password = $request->password;
        }
        $provider->status = $request->status;
        $provider->save();
        return redirect()->back()->withTrue('تم التعديل بنجاح');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param Provider $provider
     * @return Response
     * @throws Exception
     */
    public function destroy(Provider $provider)
    {
        $provider->delete();
        return redirect()->back()->withTrue('تم الحذف بنجاح');
    }
}

app/Http/Controllers/dashboard/SettingController.php
<?php

namespace App\Http\Controllers\dashboard;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Models\{Setting,Admin};
use App\Http\Requests\dashboard\{SettingRequest,ProfileRequest};
use Auth;
class SettingController extends Controller
{
    public function index()
    {
        return view('dashboard.setting.index');
    }


    public function store(SettingRequest $request)
    {
       if (!request()->ajax()) {
          if (Auth::check()) {
              $inputs=$request->except('logo','password','_token');
              if ($request->password) {
                $inputs['password']=$request->password;
              }
              if ($request->hasFile('logo')) {
                  $setting=Setting::where('key','logo')->first();
                  $setting=($setting && $setting->value) ? $setting : null;
                  $inputs['logo']=uploadImg($request->logo);
              }
              foreach ($inputs as $key => $value) {
                  Setting::updateOrCreate(['key' => trim($key)],['value'=> $value]);
              }
               return redirect()->back()->withTrue('تم التعديل بنجاح');
        }else {
          abort(404);
        }
      }

    }

    public function profile()
    {
        $user = auth()->user();
        return view('dashboard.setting.profile',compact('user'));
    }

    public function updateProfile(ProfileRequest $request,Admin $admin)
    {
        $admin->name     = $request->name;
        $admin->email    = $request->email;
        if($request->password){
            $admin->password = $request->password;
        }
        $admin->save();

        return redirect()->back()->withTrue('تم تحديث الحساب بنجاح');
    }
}

resources/views/dashboard/includes/loader.blade.php
<div class="page-loader-wrapper">
    <div class="loader">
        <div class="bar1"></div>
        <div class="bar2"></div>
        <div class="bar3"></div>
        <div class="bar4"></div>
        <div class="bar5"></div>
    </div>
</div>

resources/views/dashboard/includes/navbar.blade.php
    <nav class="navbar top-navbar">
        <div class="container-fluid">

            <div class="navbar-left">
                <div class="navbar-btn">
                    <a href= "{{ route('admin_dashboard.index')  }}"   ><img src="{{asset('public/dashboard')}}/images/icon.svg" alt="Go Logo" class="img-fluid logo"></a>
                    <button type="button" class="btn-toggle-offcanvas"><i class="lnr lnr-menu fa fa-bars"></i></button>
                </div>
                <ul class="nav navbar-nav">
                    <li class="dropdown">
                        <a href="javascript:void(0);" class="dropdown-toggle icon-menu" data-toggle="dropdown">
                            <i class="icon-envelope"></i>
                            <span class="notification-dot bg-green"> {{ \App\Models\Contact::where('type','recived')->where('readed','0')->count() }} </span>
                        </a>
                        <ul class="dropdown-menu right_chat email vivify fadeIn">
                            <li class="header green">لديك  {{ \App\Models\Contact::where('type','recived')->where('readed','0')->count() }}  رسائل جديدة</li>
                           @forelse (\App\Models\Contact::where('type','recived')->where('readed','0')->get() as $item)
                                <li>
                                    <a href="javascript:void(0);">
                                        <div class="media">
                                            <div class="avtar-pic w35 bg-red"><span> {{ $item->user->name }} </span></div>
                                            <div class="media-body">
                                                <span class="name"> {{ $item->subject }} </span>
                                                <span class="message">{{ $item->content }}</span>
                                            </div>
                                        </div>
                                    </a>
                                </li>
                           @empty
                                <li>
                                    <a href="javascript:void(0);">
                                        <div class="media">
                                            لايوجد رسائل
                                        </div>
                                    </a>
                                </li>
                           @endforelse

                        </ul>
                    </li>
                    <li class="dropdown">
                        <a href="javascript:void(0);" class="dropdown-toggle icon-menu" data-toggle="dropdown">
                            <i class="icon-bell"></i>
                            <span class="notification-dot bg-azura">0</span>
                        </a>
                        <ul class="dropdown-menu feeds_widget vivify fadeIn">
                            <li class="header blue">لديك  0 إشعارات جديدة</li>
                            {{--  <li>
                                <a href="javascript:void(0);">
                                    <div class="feeds-left bg-red"><i class="fa fa-check"></i></div>
                                    <div class="feeds-body">
                                        <h4 class="title text-danger">Issue Fixed <small class="float-right text-muted">9:10 AM</small></h4>
                                        <small>WE have fix all Design bug with Responsive</small>
                                    </div>
                                </a>
                            </li>  --}}

                        </ul>
                    </li>
                    {{--  <li class="dropdown language-menu">
                        <a href="javascript:void(0);" class="dropdown-toggle icon-menu" data-toggle="dropdown">
                            <i class="fa fa-language"></i>
                        </a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <a class="dropdown-item pt-2 pb-2" href="#"><img src="{{asset('dashboard')}}/images/flag/us.svg " class="w20 mr-2 rounded-circle"> US English</a>
                            <a class="dropdown-item pt-2 pb-2" href="#"><img src="{{asset('dashboard')}}/images/flag/gb.svg " class="w20 mr-2 rounded-circle"> UK English</a>
                            <div class="dropdown-divider"></div>
                            <a class="dropdown-item pt-2 pb-2" href="#"><img src="{{asset('dashboard')}}/images/flag/russia.svg " class="w20 mr-2 rounded-circle"> Russian</a>
                            <a class="dropdown-item pt-2 pb-2" href="#"><img src="{{asset('dashboard')}}/images/flag/arabia.svg " class="w20 mr-2 rounded-circle"> Arabic</a>
                            <a class="dropdown-item pt-2 pb-2" href="#"><img src="{{asset('dashboard')}}/images/flag/france.svg " class="w20 mr-2 rounded-circle"> French</a>
                        </div>
                    </li>  --}}
                    {{--  <li><a href="javascript:void(0);" class="megamenu_toggle icon-menu" title="Mega Menu">Mega</a></li>
                    <li class="p_social"><a href="page-social.html" class="social icon-menu" title="News">Social</a></li>
                    <li class="p_news"><a href="page-news.html" class="news icon-menu" title="News">News</a></li>
                    <li class="p_blog"><a href="page-blog.html" class="blog icon-menu" title="Blog">Blog</a></li>  --}}
                </ul>
            </div>

            <div class="navbar-right">
                <div id="navbar-menu">
                    <ul class="nav navbar-nav">
                        {{--  <li><a href="javascript:void(0);" class="search_toggle icon-menu" title="Search Result"><i class="icon-magnifier"></i></a></li>  --}}
                        {{--  <li><a href="javascript:void(0);" class="right_toggle icon-menu" title="Right Menu"><i class="icon-bubbles"></i><span class="notification-dot bg-pink">2</span></a></li>  --}}
                        <li><a href="{{ route('admin_dashboard.logout') }}" class="icon-menu"><i class="icon-power"></i></a></li>
                    </ul>
                </div>
            </div>
        </div>
        <div class="progress-container"><div class="progress-bar" id="myBar"></div></div>
    </nav>

resources/views/dashboard/includes/sidebar.blade.php
    <div id="left-sidebar" class="sidebar">
        <div class="navbar-brand">
            <a href="{{route('admin_dashboard.index')}}">  <img src="{{asset('public/dashboard')}}/images/icon.svg" alt="Oculux Logo" class="img-fluid logo"><span> GO APP </span></a>
            <button type="button" class="btn-toggle-offcanvas btn btn-sm float-right"><i class="lnr lnr-menu icon-close"></i></button>
        </div>
        <div class="sidebar-scroll">
            <div class="user-account">
                <div class="user_div">
                    <img src="{{asset('public/dashboard')}}/images/user.png" class="user-photo" alt="User Profile Picture">
                </div>
                <div class="dropdown">
                    <span>مرحبا,</span>
                    <a href="{{ route('admin_dashboard.setting.profile') }}" class="dropdown-toggle user-name" data-toggle="dropdown"><strong> إسم المستخدم </strong></a>
                    <ul class="dropdown-menu dropdown-menu-right account vivify flipInY">
                        <li><a href="{{ route('admin_dashboard.setting.profile') }}"><i class="icon-user"></i> حسابي </a></li>
                        <li><a href="{{ route('admin_dashboard.contact.index') }}"><i class="icon-envelope-open"></i>الرسائل</a></li>
                        <li><a href="{{ route('admin_dashboard.setting.index') }}"><i class="icon-settings"></i>الإعدادات</a></li>
                        <li class="divider"></li>
                        <li><a href="{{ route('admin_dashboard.logout') }}"><i class="icon-power"></i>تسجيل الخروج</a></li>
                    </ul>
                </div>
            </div>
            <nav id="left-sidebar-nav" class="sidebar-nav">
                <ul id="main-menu" class="metismenu">
                    <li class="header">القوائم</li>
                    <li class="active">
                        <a href="#myPage" ><i class="icon-home"></i><span>الرئيسية</span></a>
                    </li>

                    {{--  <li class="header">App</li>  --}}

                    <li>
                        <a href="#service" class="has-arrow"><i class="icon-book-open"></i><span>الآقسام الرئيسية للخدمات</span></a>
                        <ul>
                            <li><a href="{{ route('admin_dashboard.service.index') }}"> عرض الكل</a></li>
                            <li><a href="{{ route('admin_dashboard.service.create') }}">إضافة</a></li>
                        </ul>
                    </li>

                    <li>
                        <a href="#subservices" class="has-arrow"><i class="icon-bubbles"></i><span>الآقسام الفرعيه للخدمات</span></a>
                        <ul>
                            <li><a href="{{route('admin_dashboard.subservice.index')}}">عرض الكل </a></li>
                            <li><a href="{{route('admin_dashboard.subservice.create')}}">إضافة</a></li>
                        </ul>
                    </li>

                    <li>
                        <a href="#providers" class="has-arrow"><i class="icon-tag"></i><span>مقدمين الخدمات</span></a>
                        <ul>
                            <li><a href="{{route('admin_dashboard.provider.index')}}">عرض الكل</a></li>
                            <li><a href="{{route('admin_dashboard.provider.create')}}"> إضافة </a></li>
                        </ul>
                    </li>
                    <li>
                        <a href="#uiComponents" class="has-arrow"><i class="icon-diamond"></i><span>المستخدمين</span></a>
                        <ul>
                            <li><a href="{{route('admin_dashboard.user.index')}}"> عرض الكل </a></li>
                            <li><a href="{{route('admin_dashboard.user.create') }}">إضافة</a></li>
                        </ul>
                    </li>
                    <li>
                        <a href="#forms" class="has-arrow"><i class="icon-pencil"></i><span> الطلبات</span></a>
                        <ul>
                            <li><a href="{{route('admin_dashboard.order.index')}}">عرض الكل</a></li>
                            <li><a href="{{route('admin_dashboard.order.create')}}">إضافة</a></li>
                        </ul>
                    </li>
                    <li>
                        <a href="#forms" class="has-arrow"><i class="icon-pencil"></i><span>العروض</span></a>
                        <ul>
                            <li><a href="{{route('admin_dashboard.offers.index')}}">عرض الكل</a></li>
                            <li><a href="{{route('admin_dashboard.offers.create')}}">إضافة</a></li>
                        </ul>
                    </li>
                    <li>
                        <a href="#Tables" class="has-arrow"><i class="icon-layers"></i><span>التواصل </span></a>
                        <ul>
                            <li><a href="{{route('admin_dashboard.contact.index')}}">عرض الكل</a></li>
                            <li><a href="{{route('admin_dashboard.contact.create')}}">إضافة</a></li>
                        </ul>
                    </li>
                    <li>
                        <a href="#charts" class="has-arrow"><i class="icon-pie-chart"></i><span> الإعدادات </span></a>
                        <ul>
                            <li><a href="{{route('admin_dashboard.setting.index')}}">عرض الكل </a></li>
                            {{--  <li><a href="javascript:void(0);">إضافة</a></li>  --}}
                        </ul>
                    </li>
                    {{--  <li>
                        <a href="#Authentication" class="has-arrow"><i class="icon-lock"></i><span>قسم ٣</span></a>
                        <ul>
                            <li><a href="javascript:void(0);">عرض الكل</a></li>
                            <li><a href="javascript:void(0);">إضافة</a></li>
                        </ul>
                    </li>
                    <li>
                        <a href="#Pages" class="has-arrow"><i class="icon-docs"></i><span>قسم ٤</span></a>
                        <ul>
                            <li><a href="javascript:void(0);">عرض الكل</a></li>
                            <li><a href="javascript:void(0);">إضافة</a></li>
                        </ul>
                    </li>  --}}
                </ul>
            </nav>
        </div>
    </div>

resources/views/dashboard/includes/styles.blade.php
    <link rel="icon" href="favicon.ico" type="image/x-icon">
    <!-- VENDOR CSS -->
    <link rel="stylesheet" href="{{asset('public/dashboard')}}/vendor/bootstrap/css/bootstrap.min.css">
    <link rel="stylesheet" href="{{asset('public/dashboard')}}/vendor/font-awesome/css/font-awesome.min.css">
    <link rel="stylesheet" href="{{asset('public/dashboard')}}/vendor/animate-css/vivify.min.css">
    <link rel="stylesheet" href="{{asset('public/dashboard')}}/vendor/toastr/toastr.min.css">

    <link rel="stylesheet" href="{{asset('public/dashboard')}}/vendor/c3/c3.min.css"/>

    <!-- MAIN CSS -->
    <link rel="stylesheet" href="{{asset('public/dashboard')}}/css/site.min.css">
    @yield('css')